### ISSUE TITLE
Bug in _get_channel_scale() method

### ISSUE THREAD

**Issue by darkfeffy** [tspspi/pymso5000#3]
I have a Rigol MSO5074. Running this code snippet below results in the following error:

```
from pymso5000.mso5000 import MSO5000
with MSO5000(address = "10.5.180.106") as mso:
   x = mso.get_channel_scale(channel=1)
```
Error message:

> File "\local-packages\Python310\site-packages\pymso5000\mso5000.py", line 363, in _get_channel_scale
>     scalefactor = self._get_channel_probe_ratio(self, channel)
> TypeError: MSO5000._get_channel_probe_ratio() takes 2 positional arguments but 3 were given

I tracked down the problem to this line in _get_channel_scale() method. Removing the 'self' argument resolves the problem
![image](https://github.com/user-attachments/assets/4d9d290c-7448-4a9f-b5b4-d2bea8233e71)

**Comment by tspspi** [comment]
Many thanks for pointing out - yes this was a stupid mistake and I never caught it since we never used this routine. Fixed (in ```65cb03e```) and the fixed version should also be on pypi soon (```0.0.9```) when the build system has finished packaging ...
